### ISSUE TITLE
Submission process for intermediate ranking (deadline July 4th 2018)

### ISSUE THREAD

**Issue by monperrus** [KTH/CodRep-competition#27]
- as of now, and before July 4th, you send us your solution:
  - by adding us as collaborator to your Github/Gitlab/Bitbucket project (preferred, so as to discuss on the issue tracker directly)
  - or by sending an archive by email, with the code (source or binary) and instructions on how to compile or install the dependencies
- your program must be a local computation, you cannot use the network to download data or ask a server. The network will be cut during the evaluation on the hidden dataset.
- we execute your tool on the hidden dataset
- if we have problems in compiling or executing your code, we further discuss with you in an incremental manner.

Machine used for evaluation: Ubuntu 18.04 LTS, CPU Intel 2299MHZ, 16 GB RAM

Don't hesitate to comment here about the process.

**Comment by chenzimin** [comment]
Closed since intermediate ranking is over.
