### ISSUE TITLE
Add explanation about loss function in case of several predictions

### ISSUE THREAD

**Issue by EgorBu** [KTH/CodRep-competition#5]
Hello,
Thank you for a great competition!
One thing is not very clear to me - how loss function is computed in case of prediction several lines per file [here](https://github.com/KTH/CodRep-competition#loss-function).
As I understand it will be minimal loss among all predictions from [here](https://github.com/KTH/CodRep-competition/blob/master/Baseline/evaluate.py#L116). Is it correct?

**Comment by chenzimin** [comment]
Yes, when the algorithm predicts several lines, the minimal loss of all prediction will be chosen when calculating the average line error. 

This is from the intuition that the user will only choose the most relevant answers and the rest does not really matter. As long as the number of predictions per files is limited to some small number, like outputting top 5 predictions.

I would add an explanation for loss function in case of multiline predictions. Thanks.

**Comment by chenzimin** [comment]
Added explanation for loss function in case of multiline predictions in commit [697bfcf](https://github.com/KTH/CodRep-competition/commit/697bfcf367fb1d773f53d913f43823bf15b58f25)
