### ISSUE TITLE
Add explanation about hidden dataset

### ISSUE THREAD

**Issue by EgorBu** [KTH/CodRep-competition#6]
Hello,
Thank you for a great competition!
May you add additional information about `hidden dataset` from [here](https://github.com/KTH/CodRep-competition#the-winners).
Offtopic: I recommend using kaggle-style approach and publish test dataset without solutions, so you can receive predictions and publish public score and compute a private score.

**Comment by monperrus** [comment]
> I recommend using kaggle-style approach and publish test dataset without solutions, so you can receive predictions and publish public score and compute a private score.

Excellent suggestion, thanks, see #7

>  May you add additional information about hidden dataset from here.

Could you elaborate? What do you want to know exactly?

**Comment by EgorBu** [comment]
I couldn't understand from documentation what hidden dataset is and where it's located. They're 2 datasets available in this repository - is one of them hidden dataset?

**Comment by monperrus** [comment]
The scores are computed on the dataset present in this repository. 
We also have a hidden dataset, which is not present in this repository. 
It will be taken into account for the final ranking in order to control overfitting.

See ff4dd309d3c0b6d82a4346951764a15cbc9eeda7

**Comment by EgorBu** [comment]
Yes, thank you!
Can you explain when&how hidden dataset can be used for submission?
