### ISSUE TITLE
predicting all lines results in a minimum loss 

### ISSUE THREAD

**Issue by monperrus** [KTH/CodRep-competition#8]
if several predictions, the loss function should be average of maximum loss

**Comment by chenzimin** [comment]
Change to single prediction per file, see commit [5a54e63](https://github.com/KTH/CodRep-competition/commit/5a54e639dbdb66a55ea87382a7974bcda21c584a) and [2c5d33b](https://github.com/KTH/CodRep-competition/commit/2c5d33bcb3f3845158c65a370e1e393c4eff35f9).
